import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { api } from '../api';

import DragDropUpload from '../components/DragDropUpload';

export default function ProjectSetup() {
  const navigate = useNavigate();
  const [form, setForm] = useState({
    name: '',
    brand_name: '',
    niche: '',
    product_description: '',
    sales_page_content: '',
  });
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);

  // Sales page upload state — PDF upload is the most reliable path.
  const [salesInputMode, setSalesInputMode] = useState('upload'); // 'paste' | 'upload'
  const [uploadedFile, setUploadedFile] = useState(null);

  // Auto-describe state
  const [describing, setDescribing] = useState(false);
  const [descAutoGenerated, setDescAutoGenerated] = useState(false);

  const handleChange = (e) => {
    setForm(prev => ({ ...prev, [e.target.name]: e.target.value }));
    if (e.target.name === 'product_description') {
      setDescAutoGenerated(false);
    }
  };

  // Auto-generate product description from sales page content
  const autoDescribe = async (salesContent) => {
    if (!salesContent || salesContent.length < 50) return;

    setDescribing(true);
    try {
      const result = await api.autoDescribe(salesContent);
      setForm(prev => ({ ...prev, product_description: result.description }));
      setDescAutoGenerated(true);
    } catch (err) {
      // Non-blocking — if it fails, user can still type manually
      console.warn('Auto-describe failed:', err.message);
    } finally {
      setDescribing(false);
    }
  };

  // Trigger auto-describe when switching from paste mode (after user pastes content)
  const handleSalesContentBlur = () => {
    if (form.sales_page_content && !form.product_description) {
      autoDescribe(form.sales_page_content);
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');
    if (!form.name.trim() || !form.brand_name.trim()) {
      setError('Product Name and Brand Name are both required.');
      return;
    }
    setLoading(true);

    try {
      const project = await api.createProject(form);
      navigate(`/projects/${project.id}`);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      <div className="max-w-2xl mx-auto fade-in">
        <div className="mb-6">
          <h1 className="text-2xl font-serif font-[420] text-ed-ink tracking-tight">New Project</h1>
          <p className="text-[13px] text-ed-ink2 mt-0.5">Set up a new ad creative project</p>
        </div>

        {error && (
          <div className="bg-ed-rust/10 border border-ed-rust/30 text-ed-rust text-[13px] rounded-xl p-3 mb-4">
            {error}
          </div>
        )}

        <form onSubmit={handleSubmit} className="ed-card p-6 space-y-5">
          {/* Product Name (stored as `name`) */}
          <div>
            <label className="block text-[13px] font-medium text-ed-ink2 mb-1.5">
              Product Name <span className="text-ed-rust">*</span>
            </label>
            <input
              name="name"
              value={form.name}
              onChange={handleChange}
              className="input-apple !border-ed-line focus:!ring-ed-accent/20 focus:!border-ed-accent"
              required
              placeholder="e.g., Focus Supplement X"
            />
            <p className="text-[11px] text-ed-ink3 mt-1">What is being sold.</p>
          </div>

          {/* Brand Name */}
          <div>
            <label className="block text-[13px] font-medium text-ed-ink2 mb-1.5">
              Brand Name <span className="text-ed-rust">*</span>
            </label>
            <input
              name="brand_name"
              value={form.brand_name}
              onChange={handleChange}
              className="input-apple !border-ed-line focus:!ring-ed-accent/20 focus:!border-ed-accent"
              required
              placeholder="e.g., NeuroLabs"
            />
            <p className="text-[11px] text-ed-ink3 mt-1">Who sells it. Shown as the primary label on the project dashboard.</p>
          </div>

          <div>
            <label className="block text-[13px] font-medium text-ed-ink2 mb-1.5">Niche</label>
            <input
              name="niche"
              value={form.niche}
              onChange={handleChange}
              className="input-apple !border-ed-line focus:!ring-ed-accent/20 focus:!border-ed-accent"
              placeholder="e.g., Nootropics / Brain Health"
            />
          </div>

          {/* Sales Page Content */}
          <div>
            <div className="flex items-center justify-between mb-1.5">
              <label className="block text-[13px] font-medium text-ed-ink2">Sales Page Content</label>
              <div className="segmented-control">
                <button
                  type="button"
                  onClick={() => setSalesInputMode('upload')}
                  className={salesInputMode === 'upload' ? 'active' : ''}
                >
                  Upload
                </button>
                <button
                  type="button"
                  onClick={() => setSalesInputMode('paste')}
                  className={salesInputMode === 'paste' ? 'active' : ''}
                >
                  Paste
                </button>
              </div>
            </div>

            {salesInputMode === 'upload' && (
              <div>
                <div className="mb-3 rounded-xl border border-ed-line bg-ed-bg p-4 text-[13px] text-ed-ink2">
                  <p className="font-medium text-ed-ink mb-1">Turn a web page into a PDF</p>
                  <ol className="list-decimal list-inside space-y-1 text-[12px] text-ed-ink2">
                    <li>Open the sales page in your browser.</li>
                    <li>Press Cmd+P on Mac or Ctrl+P on Windows.</li>
                    <li>Choose Save as PDF, then upload that PDF below.</li>
                  </ol>
                  <p className="mt-3 text-[12px] text-ed-ink3">
                    If browser print does not capture the page well, search the internet for a free web page to PDF converter, paste the public sales-page URL there, download the PDF, and upload it here.
                  </p>
                  <p className="mt-2 text-[12px] text-ed-rust">
                    Use third-party PDF services only for public pages. For private or customer-sensitive pages, use your browser's Save as PDF option or paste the text manually.
                  </p>
                </div>
                <DragDropUpload
                  label="Drop your PDP / Sales Page here, or click to browse"
                  sublabel="PDF is recommended. TXT, HTML, DOCX, Markdown, CSV, JSON, XML, and spreadsheets are also supported."
                  accept=".pdf,.docx,.epub,.mobi,.txt,.html,.htm,.md,.csv,.json,.xml,.rtf,.xls,.xlsx"
                  onTextExtracted={(result) => {
                    setForm(prev => ({ ...prev, sales_page_content: result.text }));
                    setUploadedFile({ name: result.filename, charCount: result.charCount });
                    autoDescribe(result.text);
                  }}
                  successMessage={uploadedFile ? `${uploadedFile.name} (${uploadedFile.charCount.toLocaleString()} chars)` : undefined}
                  status={uploadedFile ? 'success' : undefined}
                />
                {/* Show extracted content preview */}
                {form.sales_page_content && uploadedFile && (
                  <div className="mt-3">
                    <div className="flex items-center justify-between mb-1">
                      <span className="text-[12px] text-ed-ink3">Extracted content preview</span>
                      <button
                        type="button"
                        onClick={() => setSalesInputMode('paste')}
                        className="text-[12px] text-ed-accent hover:text-ed-accent transition-colors"
                      >
                        Edit text
                      </button>
                    </div>
                    <div className="bg-ed-bg border border-black/5 rounded-xl p-3 max-h-32 overflow-y-auto text-[12px] text-ed-ink2 whitespace-pre-wrap scrollbar-thin">
                      {form.sales_page_content.slice(0, 1000)}
                      {form.sales_page_content.length > 1000 ? '...' : ''}
                    </div>
                  </div>
                )}
              </div>
            )}

            {salesInputMode === 'paste' && (
              <div>
                <textarea
                  name="sales_page_content"
                  value={form.sales_page_content}
                  onChange={handleChange}
                  onBlur={handleSalesContentBlur}
                  rows={8}
                  className="input-apple !border-ed-line focus:!ring-ed-accent/20 focus:!border-ed-accent resize-none"
                  placeholder="Paste the text content from your sales page here..."
                />
              </div>
            )}

          </div>

          {/* Product Description */}
          <div>
            <div className="flex items-center justify-between mb-1.5">
              <label className="block text-[13px] font-medium text-ed-ink2">Product Context</label>
              {describing && (
                <span className="text-[12px] text-ed-accent animate-pulse">Generating from sales page...</span>
              )}
              {descAutoGenerated && !describing && (
                <span className="text-[12px] text-ed-green flex items-center gap-1">
                  <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" /></svg>
                  AI-generated
                </span>
              )}
            </div>
            <textarea
              name="product_description"
              value={form.product_description}
              onChange={handleChange}
              rows={3}
              className={`input-apple !border-ed-line focus:!ring-ed-accent/20 focus:!border-ed-accent resize-none ${
                descAutoGenerated ? 'border-ed-green/30 bg-ed-green/5' : ''
              }`}
              placeholder={form.sales_page_content
                ? 'Will be auto-generated from your sales page content...'
                : 'Add sales page content first, or type a description manually'}
            />
            <p className="text-[11px] text-ed-ink3 mt-1.5">
              This helps ad generation, Creative Director angles, QA, and research docs understand what you sell.
            </p>
            {!form.product_description && form.sales_page_content && !describing && (
              <button
                type="button"
                onClick={() => autoDescribe(form.sales_page_content)}
                className="text-[12px] text-ed-accent hover:text-ed-accent mt-1.5 transition-colors"
              >
                Generate description from sales page
              </button>
            )}
          </div>


          <div className="flex flex-col sm:flex-row gap-3 pt-2">
            <button
              type="submit"
              disabled={loading}
              className="px-4 py-2 rounded-[7px] text-[13px] bg-ed-accent text-white hover:bg-ed-accent/90 transition-colors"
            >
              {loading ? 'Creating...' : 'Create Project'}
            </button>
            <button
              type="button"
              onClick={() => navigate('/')}
              className="ed-ghost"
            >
              Cancel
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
