import { useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { api } from '../api';
import { useToast } from '../components/Toast';

export default function ProjectSetup() {
  const navigate = useNavigate();
  const toast = useToast();
  const [form, setForm] = useState({
    name: '',
    brand_name: '',
    niche: '',
    product_description: '',
    sales_page_content: '',
  });
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);

  // Auto-describe state
  const [describing, setDescribing] = useState(false);
  const [descAutoGenerated, setDescAutoGenerated] = useState(false);
  const autoDescribePromiseRef = useRef(null);

  const handleChange = (e) => {
    setForm(prev => ({ ...prev, [e.target.name]: e.target.value }));
    if (e.target.name === 'product_description') {
      setDescAutoGenerated(false);
    }
  };

  // Auto-generate product description from product/offering details.
  const autoDescribe = async (salesContent) => {
    const trimmedContent = String(salesContent || '').trim();
    if (!trimmedContent || trimmedContent.length < 50) return '';
    if (autoDescribePromiseRef.current?.content === trimmedContent) {
      return autoDescribePromiseRef.current.promise;
    }

    setDescribing(true);
    let promise;
    promise = (async () => {
      try {
        const result = await api.autoDescribe(trimmedContent);
        const description = result.description || '';
        setForm(prev => ({ ...prev, product_description: description }));
        setDescAutoGenerated(true);
        setError('');
        return description;
      } catch (err) {
        console.warn('Auto-describe failed:', err.message);
        toast.error(err.message);
        setError(err.message);
        throw err;
      } finally {
        if (autoDescribePromiseRef.current?.promise === promise) {
          autoDescribePromiseRef.current = null;
          setDescribing(false);
        }
      }
    })();
    autoDescribePromiseRef.current = { content: trimmedContent, promise };
    return promise;
  };

  // Trigger auto-describe after the user describes the product or offering.
  const handleSalesContentBlur = () => {
    if (form.sales_page_content && !form.product_description) {
      autoDescribe(form.sales_page_content).catch(() => {});
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');
    if (!form.name.trim() || !form.brand_name.trim()) {
      setError('Product Name and Brand Name are both required.');
      return;
    }
    setLoading(true);

    try {
      let payload = { ...form };
      if (payload.sales_page_content.trim() && !payload.product_description.trim()) {
        const generatedDescription = await autoDescribe(payload.sales_page_content);
        if (!generatedDescription.trim()) {
          const message = 'Product Context is required before creating a project. Generate it from product details or type it manually.';
          setError(message);
          toast.error(message);
          return;
        }
        payload = { ...payload, product_description: generatedDescription };
      }

      const project = await api.createProject(payload);
      navigate(`/projects/${project.id}`);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      <div className="max-w-2xl mx-auto fade-in">
        <div className="mb-6">
          <h1 className="text-2xl font-serif font-[420] text-ed-ink tracking-tight">New Project</h1>
          <p className="text-[13px] text-ed-ink2 mt-0.5">Set up a new ad creative project</p>
        </div>

        {error && (
          <div className="bg-ed-rust/10 border border-ed-rust/30 text-ed-rust text-[13px] rounded-xl p-3 mb-4">
            {error}
          </div>
        )}

        <form onSubmit={handleSubmit} className="ed-card p-6 space-y-5">
          {/* Product Name (stored as `name`) */}
          <div>
            <label className="block text-[13px] font-medium text-ed-ink2 mb-1.5">
              Product Name <span className="text-ed-rust">*</span>
            </label>
            <input
              name="name"
              value={form.name}
              onChange={handleChange}
              className="input-apple !border-ed-line focus:!ring-ed-accent/20 focus:!border-ed-accent"
              required
              placeholder="e.g., Focus Supplement X"
            />
            <p className="text-[11px] text-ed-ink3 mt-1">What is being sold.</p>
          </div>

          {/* Brand Name */}
          <div>
            <label className="block text-[13px] font-medium text-ed-ink2 mb-1.5">
              Brand Name <span className="text-ed-rust">*</span>
            </label>
            <input
              name="brand_name"
              value={form.brand_name}
              onChange={handleChange}
              className="input-apple !border-ed-line focus:!ring-ed-accent/20 focus:!border-ed-accent"
              required
              placeholder="e.g., NeuroLabs"
            />
            <p className="text-[11px] text-ed-ink3 mt-1">Who sells it. Shown as the primary label on the project dashboard.</p>
          </div>

          <div>
            <label className="block text-[13px] font-medium text-ed-ink2 mb-1.5">Niche</label>
            <input
              name="niche"
              value={form.niche}
              onChange={handleChange}
              className="input-apple !border-ed-line focus:!ring-ed-accent/20 focus:!border-ed-accent"
              placeholder="e.g., Nootropics / Brain Health"
            />
          </div>

          {/* Product / Offering Details */}
          <div>
            <label className="block text-[13px] font-medium text-ed-ink2 mb-1.5">
              Describe the product or offering
            </label>
            <textarea
              name="sales_page_content"
              value={form.sales_page_content}
              onChange={handleChange}
              onBlur={handleSalesContentBlur}
              rows={8}
              className="input-apple !border-ed-line focus:!ring-ed-accent/20 focus:!border-ed-accent resize-none"
              placeholder="Provide as much detail as possible about the product being advertised — what it is, who it's for, what they get, the offer, the speaker or brand, what makes it different. The more detail you provide, the better the research."
            />
          </div>

          {/* Product Description */}
          <div>
            <div className="flex items-center justify-between mb-1.5">
              <label className="block text-[13px] font-medium text-ed-ink2">Product Context</label>
              {describing && (
                <span className="text-[12px] text-ed-accent animate-pulse">Generating from product details...</span>
              )}
              {descAutoGenerated && !describing && (
                <span className="text-[12px] text-ed-green flex items-center gap-1">
                  <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" /></svg>
                  AI-generated
                </span>
              )}
            </div>
            <textarea
              name="product_description"
              value={form.product_description}
              onChange={handleChange}
              rows={3}
              className={`input-apple !border-ed-line focus:!ring-ed-accent/20 focus:!border-ed-accent resize-none ${
                descAutoGenerated ? 'border-ed-green/30 bg-ed-green/5' : ''
              }`}
              placeholder={form.sales_page_content
                ? 'Will be auto-generated from your product details...'
                : 'Add product details first, or type a description manually'}
            />
            <p className="text-[11px] text-ed-ink3 mt-1.5">
              This helps ad generation, Creative Director angles, QA, and research docs understand what you sell.
            </p>
            {!form.product_description && form.sales_page_content && !describing && (
              <button
                type="button"
                onClick={() => autoDescribe(form.sales_page_content).catch(() => {})}
                className="text-[12px] text-ed-accent hover:text-ed-accent mt-1.5 transition-colors"
              >
                Generate description from product details
              </button>
            )}
          </div>


          <div className="flex flex-col sm:flex-row gap-3 pt-2">
            <button
              type="submit"
              disabled={loading || describing}
              className="px-4 py-2 rounded-[7px] text-[13px] bg-ed-accent text-white hover:bg-ed-accent/90 transition-colors disabled:opacity-60 disabled:cursor-not-allowed"
            >
              {describing ? 'Generating product context...' : loading ? 'Creating...' : 'Create Project'}
            </button>
            <button
              type="button"
              onClick={() => navigate('/')}
              className="ed-ghost"
            >
              Cancel
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
